---
description: Pipeline for processing dnsmasq log entries
processors:
- set:
    field: ecs.version
    value: "8.6.0"
- set:
    field: event.kind
    value: "event"
- set:
    field: event.category
    value: "network"
- set:
    field: event.action
    value: "dns-query"
- set:
    field: event.outcome
    value: "success"
- rename:
    field: message
    target_field: event.original
- grok:
    field: event.original
    patterns:
    - "%{SYSLOGTIMESTAMP:_tmp.timestamp}"
    description: "Extracts syslogtimestamp from event.original"
- date:
    field: _tmp.timestamp
    formats:
    - " MMM dd HH:mm:ss"
    - " MMM  d HH:mm:ss"
    - " MMM d  HH:mm:ss"
    target_field: "@timestamp"
    description: "Parses @timestamp _tmp.timestamp" 
- grok:
    field: event.original
    patterns:
    - "%{PROG:process.name}\\[%{POSINT:process.pid}\\]: %{POSINT:_tmp.unknownint}
      %{IP:client.ip}\\/%{POSINT:client.port} %{WORD:dns.type} %{GREEDYDATA:dns.question.name}
      is (%{IP:dns.resolved_ip})?(<?%{WORD:dns.answers.type}>|%{GREEDYDATA:dns.answers.type})?"
    ignore_failure: true
    description: "Extract question replies"
- grok:
    field: event.original
    patterns:
    - "%{PROG:process.name}\\[%{POSINT:process.pid}\\]: %{POSINT:_tmp.unknownint}
      %{IP:client.ip}\\/%{POSINT:client.port} %{WORD:dns.type}\\[%{WORD:dns.question.type}\\]
      %{GREEDYDATA:dns.question.name} from %{IP:_tmp.source.ip}"
    ignore_failure: true
    description: "Extract other question replies"
- grok:
    field: event.original
    patterns:
    - "%{PROG:process.name}\\[%{POSINT:process.pid}\\]: %{POSINT:_tmp.unknownint}
      %{IP:client.ip}\\/%{POSINT:client.port} %{WORD:dns.type} %{GREEDYDATA:dns.question.name}
      to %{IP:destination.ip}"
    ignore_failure: true
    description: "Extract forwarded questions"
- convert:
    field: client.ip
    type: ip
    ignore_failure: true
    ignore_missing: true
- geoip:
    field: client.ip
    target_field: client.geo
    ignore_missing: true
- geoip:
    field: dns.resolved_ip
    target_field: dns.resolved_ip.geo
    ignore_missing: true
- geoip:
    ignore_missing: true
    field: client.ip
    target_field: client.as
    properties:
    - asn
    - organization_name
- geoip:
    field: dns.resolved_ip
    target_field: dns.resolved_ip.as
    properties:
    - asn
    - organization_name
    ignore_missing: true
- rename:
    field: client.as.asn
    target_field: client.as.number
    ignore_missing: true
- rename:
    field: client.as.organization_name
    target_field: client.as.organization.name
    ignore_missing: true
- rename:
    field: dns.resolved_ip.as.asn
    target_field: dns.resolved_ip.as.number
    ignore_missing: true
- rename:
    field: dns.resolved_ip.as.organization_name
    target_field: dns.resolved_ip.as.organization.name
    ignore_missing: true
- remove:
    field:
    - _tmp
    ignore_failure: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'